
OBJ = main.o

LIB = ../../lib/libkogata/libkogata.lib

CFLAGS = -I ./include -I ../../common/include -I ../../lib/include

LDFLAGS = -T ../linker.ld -Xlinker -Map=login.map

OUT = login.bin

include ../../rules.make
