OBJ = start.o malloc.o debug.o syscall.o user_region.o \
	mainloop.o gip.o draw.o keyboard.o

LIB = ../../common/libkogata/libkogata.lib ../../common/libalgo/libalgo.lib ../../common/libc/libc.lib

CFLAGS = -I ../include -I ../../common/include

LDFLAGS = 

OUT = libkogata.lib

include ../../rules.make
