OBJ = start.o malloc.o debug.o syscall.o user_region.o

LIB = ../../common/libkogata/libkogata.lib

CFLAGS = -I ../include -I ../../common/include

LDFLAGS = 

OUT = libkogata.lib

include ../../rules.make
